// Code generated by github.com/dashotv/golem. DO NOT EDIT.
package client

import (
	"context"

	"github.com/dashotv/fae"
	"github.com/dashotv/scry/search"
)

type MediaService struct {
	client *Client
}

// NewMedia makes a new client for accessing Media services.
func NewMediaService(client *Client) *MediaService {
	return &MediaService{
		client: client,
	}
}

type MediaIndexResponse struct {
	*Response
	Result *search.MediaSearchResponse `json:"result"`
	Total  int64                       `json:"total"`
}

func (s *MediaService) Index(ctx context.Context) (*MediaIndexResponse, error) {
	result := &MediaIndexResponse{Response: &Response{}}
	resp, err := s.client.Resty.R().
		SetContext(ctx).
		SetResult(result).
		Get("/media/")
	if err != nil {
		return nil, fae.Wrap(err, "failed to make request")
	}
	if !resp.IsSuccess() {
		return nil, fae.Errorf("%d: %v", resp.StatusCode(), resp.String())
	}
	if result.Error {
		return nil, fae.New(result.Message)
	}

	return result, nil
}
