// Code generated by github.com/dashotv/golem. DO NOT EDIT.
package client

import (
	"context"

	"github.com/dashotv/fae"
	"github.com/dashotv/scry/search"
)

type ReleasesService struct {
	client *Client
}

// NewReleases makes a new client for accessing Releases services.
func NewReleasesService(client *Client) *ReleasesService {
	return &ReleasesService{
		client: client,
	}
}

type ReleasesIndexResponse struct {
	*Response
	Result *search.ReleaseSearchResponse `json:"result"`
	Total  int64                         `json:"total"`
}

func (s *ReleasesService) Index(ctx context.Context) (*ReleasesIndexResponse, error) {
	result := &ReleasesIndexResponse{Response: &Response{}}
	resp, err := s.client.Resty.R().
		SetContext(ctx).
		SetResult(result).
		Get("/releases/")
	if err != nil {
		return nil, fae.Wrap(err, "failed to make request")
	}
	if !resp.IsSuccess() {
		return nil, fae.Errorf("%d: %v", resp.StatusCode(), resp.String())
	}
	if result.Error {
		return nil, fae.New(result.Message)
	}

	return result, nil
}
