// Code generated by github.com/dashotv/golem. DO NOT EDIT.
package client

import (
	"context"

	"github.com/dashotv/fae"
	"github.com/dashotv/scry/search"
)

type RunicService struct {
	client *Client
}

// NewRunic makes a new client for accessing Runic services.
func NewRunicService(client *Client) *RunicService {
	return &RunicService{
		client: client,
	}
}

type RunicIndexResponse struct {
	*Response
	Result *search.RunicSearchResponse `json:"result"`
	Total  int64                       `json:"total"`
}

func (s *RunicService) Index(ctx context.Context) (*RunicIndexResponse, error) {
	result := &RunicIndexResponse{Response: &Response{}}
	resp, err := s.client.Resty.R().
		SetContext(ctx).
		SetResult(result).
		Get("/runic/")
	if err != nil {
		return nil, fae.Wrap(err, "failed to make request")
	}
	if !resp.IsSuccess() {
		return nil, fae.Errorf("%d: %v", resp.StatusCode(), resp.String())
	}
	if result.Error {
		return nil, fae.New(result.Message)
	}

	return result, nil
}
