mode: release
port: 10080
cron: false
elasticsearch:
  url: http://host.docker.internal:9200
nzbgeek:
  url: https://api.nzbgeek.info/api
  key: eISG7JzxXnmWskK632mjY3CHRylfVuiX
tvdb:
  url: https://api4.thetvdb.com/v4
  key: c09e5a1f-80c2-4615-92a3-756cc8d98bfb
tmdb:
  url: https://api.themoviedb.org
  token: eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI4MGZmNTVlNTczZmMzYzA1NzBhZmEyYTZhYzUwOWIxOCIsInN1YiI6IjRiYzg4OTJhMDE3YTNjMGY5MjAwMDBlZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.aEmRHjS6k2VByAL1TB3LL1niUULDiGlAfMkRmmLg4FQ
