// Code generated by github.com/dashotv/golem. DO NOT EDIT.
package app

import (
	"net/http"
	"time"

	ginzap "github.com/gin-contrib/zap"
	"github.com/gin-gonic/gin"
)

func init() {
	initializers = append(initializers, setupRoutes)
	healthchecks["routes"] = checkRoutes
}

func checkRoutes(app *Application) error {
	// TODO: check routes
	return nil
}

func setupRoutes(app *Application) error {
	if app.Config.Mode == "release" {
		gin.SetMode(gin.ReleaseMode)
	}

	logger := app.Log.Named("routes").Desugar()

	app.Engine = gin.New()
	app.Engine.Use(
		ginzap.Ginzap(logger, time.RFC3339, true),
		ginzap.RecoveryWithZap(logger, true),
	)
	// unauthenticated routes
	app.Default = app.Engine.Group("/")
	// authenticated routes (if enabled, otherwise same as default)
	app.Router = app.Engine.Group("/")

	// if app.Config.Auth {
	// 	clerkSecret := app.Config.ClerkSecretKey
	// 	if clerkSecret == "" {
	// 		app.Log.Fatal("CLERK_SECRET_KEY is not set")
	// 	}
	//
	// 	clerkClient, err := clerk.NewClient(clerkSecret)
	// 	if err != nil {
	// 		app.Log.Fatalf("clerk: %s", err)
	// 	}
	//
	// 	app.Router.Use(requireSession(clerkClient))
	// }

	return nil
}

// Enable Auth and uncomment to use Clerk to manage auth
// also add this import: "github.com/clerkinc/clerk-sdk-go/clerk"
//
// requireSession wraps the clerk.RequireSession middleware
// func requireSession(client clerk.Client) gin.HandlerFunc {
// 	requireActiveSession := clerk.RequireSessionV2(client)
// 	return func(gctx *gin.Context) {
// 		var skip = true
// 		var handler http.HandlerFunc = func(http.ResponseWriter, *http.Request) {
// 			skip = false
// 		}
// 		requireActiveSession(handler).ServeHTTP(gctx.Writer, gctx.Request)
// 		switch {
// 		case skip:
// 			gctx.AbortWithStatusJSON(http.StatusBadRequest, gin.H{"error": "session required"})
// 		default:
// 			gctx.Next()
// 		}
// 	}
// }

func (a *Application) Routes() {
	a.Default.GET("/", a.indexHandler)
	a.Default.GET("/health", a.healthHandler)

	es := a.Router.Group("/es")
	es.GET("/", a.EsIndexHandler)
	es.GET("/media", a.EsMediaHandler)
	es.GET("/release", a.EsReleaseHandler)

	media := a.Router.Group("/media")
	media.GET("/", a.MediaIndexHandler)

	nzbs := a.Router.Group("/nzbs")
	nzbs.GET("/movie", a.NzbsMovieHandler)
	nzbs.GET("/tv", a.NzbsTvHandler)

	releases := a.Router.Group("/releases")
	releases.GET("/", a.ReleasesIndexHandler)

	search := a.Router.Group("/search")
	search.GET("/", a.SearchIndexHandler)

}

func (a *Application) indexHandler(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{
		"name": "scry",
		"routes": gin.H{
			"es":       "/es",
			"media":    "/media",
			"nzbs":     "/nzbs",
			"releases": "/releases",
			"search":   "/search",
		},
	})
}

func (a *Application) healthHandler(c *gin.Context) {
	health, err := a.Health()
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{
			"error": err.Error(),
		})
		return
	}
	c.JSON(http.StatusOK, gin.H{"name": "scry", "health": health})
}

// Es (/es)
func (a *Application) EsIndexHandler(c *gin.Context) {
	a.EsIndex(c)
}
func (a *Application) EsMediaHandler(c *gin.Context) {
	a.EsMedia(c)
}
func (a *Application) EsReleaseHandler(c *gin.Context) {
	a.EsRelease(c)
}

// Media (/media)
func (a *Application) MediaIndexHandler(c *gin.Context) {
	a.MediaIndex(c)
}

// Nzbs (/nzbs)
func (a *Application) NzbsMovieHandler(c *gin.Context) {
	a.NzbsMovie(c)
}
func (a *Application) NzbsTvHandler(c *gin.Context) {
	a.NzbsTv(c)
}

// Releases (/releases)
func (a *Application) ReleasesIndexHandler(c *gin.Context) {
	a.ReleasesIndex(c)
}

// Search (/search)
func (a *Application) SearchIndexHandler(c *gin.Context) {
	a.SearchIndex(c)
}
