// This file is autogenerated by Golem
// Do NOT make modifications, they will be lost
package app

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

func (s *Server) Routes() {
	s.Default.GET("/", homeHandler)

	media := s.Router.Group("/media")
	media.GET("/", mediaIndexHandler)

	nzbs := s.Router.Group("/nzbs")
	nzbs.GET("/movie", nzbsMovieHandler)
	nzbs.GET("/tv", nzbsTvHandler)

	releases := s.Router.Group("/releases")
	releases.GET("/", releasesIndexHandler)

	search := s.Router.Group("/search")
	search.GET("/", searchIndexHandler)

}

func homeHandler(c *gin.Context) {
	Index(c)
}

func Index(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{
		"name": "scry",
		"routes": gin.H{
			"media":    "/media",
			"nzbs":     "/nzbs",
			"releases": "/releases",
			"search":   "/search",
		},
	})
}

// /media
func mediaIndexHandler(c *gin.Context) {

	MediaIndex(c)
}

// /nzbs
func nzbsMovieHandler(c *gin.Context) {

	NzbsMovie(c)
}

func nzbsTvHandler(c *gin.Context) {

	NzbsTv(c)
}

// /releases
func releasesIndexHandler(c *gin.Context) {

	ReleasesIndex(c)
}

// /search
func searchIndexHandler(c *gin.Context) {

	SearchIndex(c)
}
