repo: github.com/dashotv/scry
name: scry
groups:
  media:
    path: /media
    routes:
      index:
        path: /
  nzbs:
    path: /nzbs
    routes:
      movie:
        path: /movie
      tv:
        path: /tv
  releases:
    path: /releases
    routes:
      index:
        path: /
  tmdb:
    name: tmdb
    path: /tmdb
    routes:
      index:
        path: /
  tvdb:
    name: tvdb
    path: /tvdb
    routes:
      index:
        path: /
