repo: github.com/dashotv/scry
name: scry
groups:
  search:
    path: /search
    routes:
      index:
        path: /
  media:
    path: /media
    routes:
      index:
        path: /
  nzbs:
    path: /nzbs
    routes:
      movie:
        path: /movie
      tv:
        path: /tv
  releases:
    path: /releases
    routes:
      index:
        path: /
