name: scry
repo: github.com/dashotv/scry
groups:
  media:
    path: /media
    routes:
      index:
        path: /
  nzbs:
    path: /nzbs
    routes:
      tv:
        path: /tv
      movie:
        path: /movie
  releases:
    path: /releases
    routes:
      index:
        path: /
